---
language: perl
perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

install:
  - cpanm --with-configure --with-develop --installdeps --notest .
  - perl Makefile.PL
  - make

script:
  - make test TEST_VERBOSE=1
  - prove -v xt

before_deploy:
  - make manifest
  - make dist

deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file: 'Broker-Async-${TRAVIS_TAG}.tar.gz'
  skip_cleanup: true
  on:
    tags: true

