on configure => sub {
    requires 'Module::CPANfile';
};

on runtime => sub {
    requires 'Class::Tiny';
    requires 'Scalar::Util';
};

on test => sub {
    requires 'Future';
    requires 'Test::Fatal';
};
